name: CI
on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v1
        with:
          path: target
          key: cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: i686-pc-windows-msvc
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - shell: bash
        run: |
          mv target/i686-pc-windows-msvc/release/extended_story.dll ./ExtendedStory.dll
          7z a -tzip release.zip ExtendedStory.dll
